plugins {
    id "com.android.application"
}

android {
    namespace "com.dimitriazzarone.chatgptmessenger"
    compileSdk 35

    defaultConfig {
        applicationId "com.dimitriazzarone.chatgptmessenger"
        minSdk 24
        targetSdk 35
        versionCode 22
        versionName "1.12"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
